In [1]:
from perceptron import *
import pandas as pd
import numpy as np

In [2]:
iris_dataset = pd.read_csv('files/iris.csv')

In [3]:
iris_validation = run_perceptron_validation_iris(
                                            dataset=iris_dataset, 
                                            column_x='Species', 
                                            column_y='setosa', 
                                            test_size=0.1)
iris_validation

{'predictions': [1, 1, -1, 1, 1, -1, 1, 1, 1, 1, 1, 1, 1, -1, -1],
 'prediction_success': '100.0%',
 'crosstab': Predicted  -1   1  All
 True                  
 -1          4   0    4
 1           0  11   11
 All         4  11   15,
 'accuracy_score': 1.0,
 'f1_score': 1.0}

# Tarefa 1 - Reexecutar train/test/split

In [4]:
iris_validation_2 = run_perceptron_validation_iris(
                                            dataset=iris_dataset, 
                                            column_x='Species', 
                                            column_y='setosa', 
                                            test_size=0.1)
iris_validation_2

{'predictions': [-1, 1, 1, 1, -1, 1, -1, 1, 1, -1, -1, 1, 1, 1, 1],
 'prediction_success': '100.0%',
 'crosstab': Predicted  -1   1  All
 True                  
 -1          5   0    5
 1           0  10   10
 All         5  10   15,
 'accuracy_score': 1.0,
 'f1_score': 1.0}

# Tarefa 2 - Alterar binarização das classes (Setosa, Versicolor, Virginica)

In [5]:
iris_validation_virginica = run_perceptron_validation_iris(
                                            dataset=iris_dataset, 
                                            column_x='Species', 
                                            column_y='virginica', 
                                            test_size=0.1)
iris_validation_virginica

{'predictions': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, -1, -1, 1],
 'prediction_success': '73.33333333333333%',
 'crosstab': Predicted  -1   1  All
 True                  
 -1          2   4    6
 1           0   9    9
 All         2  13   15,
 'accuracy_score': 0.7333333333333333,
 'f1_score': 0.6590909090909091}

In [6]:
iris_validation_versicolor = run_perceptron_validation_iris(
                                            dataset=iris_dataset, 
                                            column_x='Species', 
                                            column_y='versicolor', 
                                            test_size=0.1)
iris_validation_versicolor

{'predictions': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
 'prediction_success': '66.66666666666666%',
 'crosstab': Predicted   1  All
 True              
 -1          5    5
 1          10   10
 All        15   15,
 'accuracy_score': 0.6666666666666666,
 'f1_score': 0.4}

# Tarefa 3 - Alterar o tamanho do teste

In [7]:
iris_validation_with_greater_test_size = run_perceptron_validation_iris(
                                            dataset=iris_dataset, 
                                            column_x='Species', 
                                            column_y='setosa', 
                                            test_size=0.2)
iris_validation_with_greater_test_size

{'predictions': [1,
  1,
  1,
  1,
  1,
  1,
  -1,
  1,
  1,
  -1,
  -1,
  1,
  1,
  -1,
  1,
  1,
  1,
  1,
  -1,
  -1,
  -1,
  1,
  1,
  1,
  -1,
  1,
  -1,
  1,
  1,
  -1],
 'prediction_success': '93.33333333333333%',
 'crosstab': Predicted  -1   1  All
 True                  
 -1          8   0    8
 1           2  20   22
 All        10  20   30,
 'accuracy_score': 0.9333333333333333,
 'f1_score': 0.9206349206349207}

# Tarefa 4 - Explorar dataset UCI

 - Dataset: https://archive.ics.uci.edu/ml/datasets/Credit+Approval

In [8]:
credit_dataset = pd.read_csv('files/credit_approval.csv')
credit_dataset

ATTR_1 ATTR_2    ATTR_3 ATTR_4 ATTR_5 ATTR_6 ATTR_7  ATTR_8 ATTR_9  \
0        b  30.83      0.00      u      g      w      v    1.25      t   
1        a  58.67      4.46      u      g      q      h    3.04      t   
2        a  24.50      0.50      u      g      q      h    1.50      t   
3        b  27.83      1.54      u      g      w      v    3.75      t   
4        b  20.17   5625.00      u      g      w      v    1.71      t   
..     ...    ...       ...    ...    ...    ...    ...     ...    ...   
685      b  21.08  10085.00      y      p      e      h    1.25      f   
686      a  22.67      0.75      u      g      c      v    2.00      f   
687      a  25.25     13.50      y      p     ff     ff    2.00      f   
688      b  17.92    205.00      u      g     aa      v    0.04      f   
689      b  35.00   3375.00      u      g      c      h    8.29      f   

    ATTR_10  ATTR_11 ATTR_12 ATTR_13 ATTR_14  ATTR_15 CLASS  
0         t        1       f       g     202        0     +  
1         t        6       f       g      43      560     +  
2         f        0       f       g     280      824     +  
3         t        5       t       g     100        3     +  
4         f        0       f       s     120        0     +  
..      ...      ...     ...     ...     ...      ...   ...  
685       f        0       f       g     260        0     -  
686       t        2       t       g     200      394     -  
687       t        1       t       g     200        1     -  
688       f        0       f       g     280      750     -  
689       f        0       t       g       0        0     -  

[690 rows x 16 columns]

In [9]:
tabulated_attrs = ['1', '4', '5', '6', '7', '9', '10', '12', '13']
for attr in tabulated_attrs:
    print(credit_dataset[f'ATTR_{attr}'].unique())

['b' 'a' '?']
['u' 'y' '?' 'l']
['g' 'p' '?' 'gg']
['w' 'q' 'm' 'r' 'cc' 'k' 'c' 'd' 'x' 'i' 'e' 'aa' 'ff' 'j' '?']
['v' 'h' 'bb' 'ff' 'j' 'z' '?' 'o' 'dd' 'n']
['t' 'f']
['t' 'f']
['f' 't']
['g' 's' 'p']


# Removendo linhas com valores nulos

In [10]:
for attr in range(1,15):
    credit_dataset = credit_dataset.drop(
        credit_dataset[credit_dataset[f'ATTR_{str(attr)}'] == '?'].index)

In [11]:
for attr in tabulated_attrs:
    print(credit_dataset[f'ATTR_{attr}'].unique())

['b' 'a']
['u' 'y' 'l']
['g' 'p' 'gg']
['w' 'q' 'm' 'r' 'cc' 'k' 'c' 'd' 'x' 'i' 'e' 'aa' 'ff' 'j']
['v' 'h' 'bb' 'ff' 'j' 'z' 'o' 'dd' 'n']
['t' 'f']
['t' 'f']
['f' 't']
['g' 's' 'p']


# Transformando valores CHAR em numéricos

In [12]:
credit_dataset.dtypes

ATTR_1      object
ATTR_2      object
ATTR_3     float64
ATTR_4      object
ATTR_5      object
ATTR_6      object
ATTR_7      object
ATTR_8     float64
ATTR_9      object
ATTR_10     object
ATTR_11      int64
ATTR_12     object
ATTR_13     object
ATTR_14     object
ATTR_15      int64
CLASS       object
dtype: object

In [13]:
for attr in tabulated_attrs:
    credit_dataset[f'ATTR_{attr}'] = pd.factorize(credit_dataset[f'ATTR_{attr}'])[0]

In [14]:
credit_dataset.dtypes

ATTR_1       int64
ATTR_2      object
ATTR_3     float64
ATTR_4       int64
ATTR_5       int64
ATTR_6       int64
ATTR_7       int64
ATTR_8     float64
ATTR_9       int64
ATTR_10      int64
ATTR_11      int64
ATTR_12      int64
ATTR_13      int64
ATTR_14     object
ATTR_15      int64
CLASS       object
dtype: object

In [15]:
for attr in tabulated_attrs:
    print(credit_dataset[f'ATTR_{attr}'].unique())

[0 1]
[0 1 2]
[0 1 2]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13]
[0 1 2 3 4 5 6 7 8]
[0 1]
[0 1]
[0 1]
[0 1 2]


In [16]:
credit_dataset["CLASS"] = np.where(credit_dataset["CLASS"].astype('string') == "+", 1, -1)

In [17]:
credit_dataset["CLASS"].unique()

array([ 1, -1])

In [18]:
credit_dataset.dtypes

ATTR_1       int64
ATTR_2      object
ATTR_3     float64
ATTR_4       int64
ATTR_5       int64
ATTR_6       int64
ATTR_7       int64
ATTR_8     float64
ATTR_9       int64
ATTR_10      int64
ATTR_11      int64
ATTR_12      int64
ATTR_13      int64
ATTR_14     object
ATTR_15      int64
CLASS        int64
dtype: object

In [19]:
credit_dataset['ATTR_2']

0      30.83
1      58.67
2      24.50
3      27.83
4      20.17
       ...  
685    21.08
686    22.67
687    25.25
688    17.92
689    35.00
Name: ATTR_2, Length: 653, dtype: object

In [20]:
credit_dataset['ATTR_2'] = pd.to_numeric(credit_dataset['ATTR_2'])

In [21]:
credit_dataset.dtypes

ATTR_1       int64
ATTR_2     float64
ATTR_3     float64
ATTR_4       int64
ATTR_5       int64
ATTR_6       int64
ATTR_7       int64
ATTR_8     float64
ATTR_9       int64
ATTR_10      int64
ATTR_11      int64
ATTR_12      int64
ATTR_13      int64
ATTR_14     object
ATTR_15      int64
CLASS        int64
dtype: object

In [22]:
credit_dataset['ATTR_14']

0      202
1       43
2      280
3      100
4      120
      ... 
685    260
686    200
687    200
688    280
689      0
Name: ATTR_14, Length: 653, dtype: object

In [23]:
credit_dataset['ATTR_14'] = pd.to_numeric(credit_dataset['ATTR_14'])

In [24]:
credit_dataset.dtypes

ATTR_1       int64
ATTR_2     float64
ATTR_3     float64
ATTR_4       int64
ATTR_5       int64
ATTR_6       int64
ATTR_7       int64
ATTR_8     float64
ATTR_9       int64
ATTR_10      int64
ATTR_11      int64
ATTR_12      int64
ATTR_13      int64
ATTR_14      int64
ATTR_15      int64
CLASS        int64
dtype: object

In [25]:
credit_dataset

ATTR_1  ATTR_2    ATTR_3  ATTR_4  ATTR_5  ATTR_6  ATTR_7  ATTR_8  ATTR_9  \
0         0   30.83      0.00       0       0       0       0    1.25       0   
1         1   58.67      4.46       0       0       1       1    3.04       0   
2         1   24.50      0.50       0       0       1       1    1.50       0   
3         0   27.83      1.54       0       0       0       0    3.75       0   
4         0   20.17   5625.00       0       0       0       0    1.71       0   
..      ...     ...       ...     ...     ...     ...     ...     ...     ...   
685       0   21.08  10085.00       1       1      10       1    1.25       1   
686       1   22.67      0.75       0       0       6       0    2.00       1   
687       1   25.25     13.50       1       1      12       3    2.00       1   
688       0   17.92    205.00       0       0      11       0    0.04       1   
689       0   35.00   3375.00       0       0       6       1    8.29       1   

     ATTR_10  ATTR_11  ATTR_12  ATTR_13  ATTR_14  ATTR_15  CLASS  
0          0        1        0        0      202        0      1  
1          0        6        0        0       43      560      1  
2          1        0        0        0      280      824      1  
3          0        5        1        0      100        3      1  
4          1        0        0        1      120        0      1  
..       ...      ...      ...      ...      ...      ...    ...  
685        1        0        0        0      260        0     -1  
686        0        2        1        0      200      394     -1  
687        0        1        1        0      200        1     -1  
688        1        0        0        0      280      750     -1  
689        1        0        1        0        0        0     -1  

[653 rows x 16 columns]

In [26]:
credit_dataset = credit_dataset.reset_index()

In [27]:
credit_dataset['CLASS'].unique()

array([ 1, -1])

In [28]:
credit_dataset

index  ATTR_1  ATTR_2    ATTR_3  ATTR_4  ATTR_5  ATTR_6  ATTR_7  ATTR_8  \
0        0       0   30.83      0.00       0       0       0       0    1.25   
1        1       1   58.67      4.46       0       0       1       1    3.04   
2        2       1   24.50      0.50       0       0       1       1    1.50   
3        3       0   27.83      1.54       0       0       0       0    3.75   
4        4       0   20.17   5625.00       0       0       0       0    1.71   
..     ...     ...     ...       ...     ...     ...     ...     ...     ...   
648    685       0   21.08  10085.00       1       1      10       1    1.25   
649    686       1   22.67      0.75       0       0       6       0    2.00   
650    687       1   25.25     13.50       1       1      12       3    2.00   
651    688       0   17.92    205.00       0       0      11       0    0.04   
652    689       0   35.00   3375.00       0       0       6       1    8.29   

     ATTR_9  ATTR_10  ATTR_11  ATTR_12  ATTR_13  ATTR_14  ATTR_15  CLASS  
0         0        0        1        0        0      202        0      1  
1         0        0        6        0        0       43      560      1  
2         0        1        0        0        0      280      824      1  
3         0        0        5        1        0      100        3      1  
4         0        1        0        0        1      120        0      1  
..      ...      ...      ...      ...      ...      ...      ...    ...  
648       1        1        0        0        0      260        0     -1  
649       1        0        2        1        0      200      394     -1  
650       1        0        1        1        0      200        1     -1  
651       1        1        0        0        0      280      750     -1  
652       1        1        0        1        0        0        0     -1  

[653 rows x 17 columns]

In [29]:
output = run_perceptron_validation_credit(credit_dataset, 0.1)

In [30]:
output

{'predictions': [-1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1],
 'prediction_success': '59.09090909090909%',
 'crosstab': Predicted  -1  All
 True              
 -1         39   39
 1          27   27
 All        66   66,
 'accuracy_score': 0.5909090909090909,
 'f1_score': 0.37142857142857144}

In [31]:
output['crosstab']

Predicted  -1  All
True              
-1         39   39
1          27   27
All        66   66